language: c

sudo: required

before_install:
   - test -f .travis.d/before_install && .travis.d/before_install

install:
   - test -f .travis.d/install && .travis.d/install

script:
   - test -f .travis.d/script && .travis.d/script

