language: c

sudo: required

before_install:
   - sudo mkdir -p /home/linuxbrew
   - sudo chown "$USER" /home/linuxbrew
   - git clone https://github.com/Linuxbrew/brew.git /home/linuxbrew/.linuxbrew
   - PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
   - brew update
   - brew install glibc

script:
   - echo "success"
