language: c

sudo: required

# idea stolen from https://github.com/SwiftNIOExtras/swift-nio-irc/blob/develop/.travis.yml

before_install:   
   - [ ! -f .travis.d/before_install ] || .travis.d/before_install

install:   
   - [ ! -f .travis.d/install ] || .travis.d/install

script:   
   - [ ! -f .travis.d/script ] || .travis.d/script

